### ISSUE TITLE
Failing to process 'as:Link' and 'as:Object' in https://www.w3.org/ns/activitystreams-owl

### ISSUE THREAD

**Issue by AaronNGray** [AaronNGray/schema-dts#1]
Error: Couldn't find parent of http://www.w3.org/ns/activitystreams#Activity, http://www.w3.org/ns/activitystreams#Object with'schema-dts-gen --ontology=https://www.w3.org/ns/activitystreams-owl'

```
C:\Users\aaron\GitHub\AaronNGray\schema-dts\packages\schema-dts-gen>node bin\schema-dts-gen --ontology=https://www.w3.org/ns/activitystreams-owl
Error: Couldn't find parent of http://www.w3.org/ns/activitystreams#Activity, http://www.w3.org/ns/activitystreams#Object (available: http://www.w3.org/ns/activitystreams#Activity, http://www.w3.org/ns/activitystreams#Collection, http://www.w3.org/ns/activitystreams#CollectionPage, http://www.w3.org/ns/activitystreams#Image, http://www.w3.org/ns/activitystreams#OrderedItems, http://www.w3.org/ns/activitystreams#Relationship, http://www.w3.org/ns/activitystreams#Question, http://www.w3.org/ns/activitystreams#Profile, http://www.w3.org/ns/activitystreams#Tombstone, http://www.w3.org/ns/activitystreams#Place, http://www.w3.org/ns/activitystreams#OrderedCollectionPage, http://www.w3.org/ns/activitystreams#Accept, http://www.w3.org/ns/activitystreams#Block, http://www.w3.org/ns/activitystreams#Ignore, http://www.w3.org/ns/activitystreams#IntransitiveActivity, http://www.w3.org/ns/activitystreams#Add, http://www.w3.org/ns/activitystreams#Announce, http://www.w3.org/ns/activitystreams#Application, http://www.w3.org/ns/activitystreams#Arrive, http://www.w3.org/ns/activitystreams#Article, http://www.w3.org/ns/activitystreams#Audio, http://www.w3.org/ns/activitystreams#Document, http://www.w3.org/ns/activitystreams#OrderedCollection, http://www.w3.org/ns/activitystreams#Create, http://www.w3.org/ns/activitystreams#Delete, http://www.w3.org/ns/activitystreams#Dislike, http://www.w3.org/ns/activitystreams#Event, http://www.w3.org/ns/activitystreams#Flag, http://www.w3.org/ns/activitystreams#Follow, http://www.w3.org/ns/activitystreams#Group, http://www.w3.org/ns/activitystreams#Invite, http://www.w3.org/ns/activitystreams#Offer, http://www.w3.org/ns/activitystreams#Join, http://www.w3.org/ns/activitystreams#Leave, http://www.w3.org/ns/activitystreams#Like, http://www.w3.org/ns/activitystreams#View, http://www.w3.org/ns/activitystreams#Listen, http://www.w3.org/ns/activitystreams#Read, http://www.w3.org/ns/activitystreams#Move, http://www.w3.org/ns/activitystreams#Travel, http://www.w3.org/ns/activitystreams#Mention, http://www.w3.org/ns/activitystreams#Note, http://www.w3.org/ns/activitystreams#Page, http://www.w3.org/ns/activitystreams#Person, http://www.w3.org/ns/activitystreams#Organization, http://www.w3.org/ns/activitystreams#Reject, http://www.w3.org/ns/activitystreams#Remove, http://www.w3.org/ns/activitystreams#Service, http://www.w3.org/ns/activitystreams#TentativeAccept, http://www.w3.org/ns/activitystreams#TentativeReject, http://www.w3.org/ns/activitystreams#Undo, http://www.w3.org/ns/activitystreams#Update, http://www.w3.org/ns/activitystreams#Video)
    at Class.add (file:///C:/Users/aaron/GitHub/AaronNGray/schema-dts/packages/schema-dts-gen/dist/src/ts/class.js:135:23)
    at toClass (file:///C:/Users/aaron/GitHub/AaronNGray/schema-dts/packages/schema-dts-gen/dist/src/transform/toClass.js:25:27)
    at BuildClasses (file:///C:/Users/aaron/GitHub/AaronNGray/schema-dts/packages/schema-dts-gen/dist/src/transform/toClass.js:109:9)
    at ProcessClasses (file:///C:/Users/aaron/GitHub/AaronNGray/schema-dts/packages/schema-dts-gen/dist/src/transform/toClass.js:125:5)
    at file:///C:/Users/aaron/GitHub/AaronNGray/schema-dts/packages/schema-dts-gen/dist/src/transform/transform.js:49:25
    at Generator.next (<anonymous>)
    at file:///C:/Users/aaron/GitHub/AaronNGray/schema-dts/packages/schema-dts-gen/dist/src/transform/transform.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (file:///C:/Users/aaron/GitHub/AaronNGray/schema-dts/packages/schema-dts-gen/dist/src/transform/transform.js:3:12)
    at WriteDeclarations (file:///C:/Users/aaron/GitHub/AaronNGray/schema-dts/packages/schema-dts-gen/dist/src/transform/transform.js:47:12)
 1: 00007FF63DCEDABF node_api_throw_syntax_error+175503
 2: 00007FF63DC72496 v8::base::CPU::num_virtual_address_bits+66006
 3: 00007FF63DBFDCA9 std::basic_ios<char,std::char_traits<char> >::setstate+15241
 4: 00007FF63E764C1E v8::internal::Builtins::name+314382
 5: 00007FF63E764818 v8::internal::Builtins::name+313352
 6: 00007FF63E764AF9 v8::internal::Builtins::name+314089
 7: 00007FF63E764950 v8::internal::Builtins::name+313664
 8: 00007FF63E855F61 v8::internal::SetupIsolateDelegate::SetupHeap+606961
 9: 00007FF63E7CD780 v8::internal::SetupIsolateDelegate::SetupHeap+47888
10: 00007FF63E8AEF58 v8::internal::SetupIsolateDelegate::SetupHeap+971496
11: 00007FF63E7F5277 v8::internal::SetupIsolateDelegate::SetupHeap+210439
12: 00007FF63E7CBDFB v8::internal::SetupIsolateDelegate::SetupHeap+41355
13: 00007FF63E67C0F0 v8::internal::Execution::CallWasm+1664
14: 00007FF63E67C20B v8::internal::Execution::CallWasm+1947
15: 00007FF63E67CFBA v8::internal::Execution::TryCallScript+346
16: 00007FF63E654B32 v8::internal::MicrotaskQueue::RunMicrotasks+370
17: 00007FF63E6548FA v8::internal::MicrotaskQueue::PerformCheckpointInternal+74
18: 00007FF63E764C1E v8::internal::Builtins::name+314382
19: 00007FF63E764818 v8::internal::Builtins::name+313352
20: 00007FF63E764AF9 v8::internal::Builtins::name+314089
21: 00007FF63E764950 v8::internal::Builtins::name+313664
22: 00007FF63E855F61 v8::internal::SetupIsolateDelegate::SetupHeap+606961
23: 00007FF5BEA6E914
```

**Comment by AaronNGray** [comment]
```
C:\Users\aaron\GitHub\AaronNGray\schema-dts\packages\schema-dts-gen>node bin\schema-dts-gen --ontology=https://www.w3.org/ns/activitystreams-owl
Class.add(value:Quad = Quad {
  id: '',
  _subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Activity' },
  _predicate: NamedNode { id: 'http://www.w3.org/2000/01/rdf-schema#subClassOf' },
  _object: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Object' },
  _graph: DefaultGraph { id: '' }
}  classMap:ClassMap =  Map(53) {
  'http://www.w3.org/ns/activitystreams#Activity' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Activity' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {},
    _comment: 'An Object representing some form of Action that has been taken'
  },
  'http://www.w3.org/ns/activitystreams#Collection' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Collection' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#CollectionPage' => Class {
    subject: NamedNode {
      id: 'http://www.w3.org/ns/activitystreams#CollectionPage'
    },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Image' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Image' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#OrderedItems' => Class {
    subject: NamedNode {
      id: 'http://www.w3.org/ns/activitystreams#OrderedItems'
    },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Relationship' => Class {
    subject: NamedNode {
      id: 'http://www.w3.org/ns/activitystreams#Relationship'
    },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Question' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Question' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Profile' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Profile' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Tombstone' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Tombstone' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Place' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Place' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#OrderedCollectionPage' => Class {
    subject: NamedNode {
      id: 'http://www.w3.org/ns/activitystreams#OrderedCollectionPage'
    },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Accept' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Accept' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Block' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Block' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Ignore' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Ignore' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#IntransitiveActivity' => Class {
    subject: NamedNode {
      id: 'http://www.w3.org/ns/activitystreams#IntransitiveActivity'
    },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Add' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Add' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Announce' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Announce' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Application' => Class {
    subject: NamedNode {
      id: 'http://www.w3.org/ns/activitystreams#Application'
    },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Arrive' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Arrive' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Article' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Article' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Audio' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Audio' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Document' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Document' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#OrderedCollection' => Class {
    subject: NamedNode {
      id: 'http://www.w3.org/ns/activitystreams#OrderedCollection'
    },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Create' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Create' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Delete' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Delete' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Dislike' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Dislike' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Event' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Event' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Flag' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Flag' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Follow' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Follow' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Group' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Group' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Invite' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Invite' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Offer' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Offer' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Join' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Join' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Leave' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Leave' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Like' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Like' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#View' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#View' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Listen' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Listen' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Read' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Read' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Move' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Move' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Travel' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Travel' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Mention' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Mention' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Note' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Note' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Page' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Page' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Person' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Person' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Organization' => Class {
    subject: NamedNode {
      id: 'http://www.w3.org/ns/activitystreams#Organization'
    },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Reject' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Reject' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Remove' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Remove' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Service' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Service' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#TentativeAccept' => Class {
    subject: NamedNode {
      id: 'http://www.w3.org/ns/activitystreams#TentativeAccept'
    },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#TentativeReject' => Class {
    subject: NamedNode {
      id: 'http://www.w3.org/ns/activitystreams#TentativeReject'
    },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Undo' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Undo' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Update' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Update' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  },
  'http://www.w3.org/ns/activitystreams#Video' => Class {
    subject: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Video' },
    _typedefs: [],
    _isDataType: false,
    _explicitlyMarkedAsClass: false,
    children: [],
    _parents: [],
    _props: Set(0) {},
    _enums: Set(0) {},
    _supersededBy: Set(0) {}
  }
} )
s:{subClassOf: NamedNode} = {
  subClassOf: NamedNode { id: 'http://www.w3.org/ns/activitystreams#Object' }
}
classMap.get(s.subClassOf.id) = undefined
Error: Couldn't find parent of http://www.w3.org/ns/activitystreams#Activity, http://www.w3.org/ns/activitystreams#Object (available: http://www.w3.org/ns/activitystreams#Activity, http://www.w3.org/ns/activitystreams#Collection, http://www.w3.org/ns/activitystreams#CollectionPage, http://www.w3.org/ns/activitystreams#Image, http://www.w3.org/ns/activitystreams#OrderedItems, http://www.w3.org/ns/activitystreams#Relationship, http://www.w3.org/ns/activitystreams#Question, http://www.w3.org/ns/activitystreams#Profile, http://www.w3.org/ns/activitystreams#Tombstone, http://www.w3.org/ns/activitystreams#Place, http://www.w3.org/ns/activitystreams#OrderedCollectionPage, http://www.w3.org/ns/activitystreams#Accept, http://www.w3.org/ns/activitystreams#Block, http://www.w3.org/ns/activitystreams#Ignore, http://www.w3.org/ns/activitystreams#IntransitiveActivity, http://www.w3.org/ns/activitystreams#Add, http://www.w3.org/ns/activitystreams#Announce, http://www.w3.org/ns/activitystreams#Application, http://www.w3.org/ns/activitystreams#Arrive, http://www.w3.org/ns/activitystreams#Article, http://www.w3.org/ns/activitystreams#Audio, http://www.w3.org/ns/activitystreams#Document, http://www.w3.org/ns/activitystreams#OrderedCollection, http://www.w3.org/ns/activitystreams#Create, http://www.w3.org/ns/activitystreams#Delete, http://www.w3.org/ns/activitystreams#Dislike, http://www.w3.org/ns/activitystreams#Event, http://www.w3.org/ns/activitystreams#Flag, http://www.w3.org/ns/activitystreams#Follow, http://www.w3.org/ns/activitystreams#Group, http://www.w3.org/ns/activitystreams#Invite, http://www.w3.org/ns/activitystreams#Offer, http://www.w3.org/ns/activitystreams#Join, http://www.w3.org/ns/activitystreams#Leave, http://www.w3.org/ns/activitystreams#Like, http://www.w3.org/ns/activitystreams#View, http://www.w3.org/ns/activitystreams#Listen, http://www.w3.org/ns/activitystreams#Read, http://www.w3.org/ns/activitystreams#Move, http://www.w3.org/ns/activitystreams#Travel, http://www.w3.org/ns/activitystreams#Mention, http://www.w3.org/ns/activitystreams#Note, http://www.w3.org/ns/activitystreams#Page, http://www.w3.org/ns/activitystreams#Person, http://www.w3.org/ns/activitystreams#Organization, http://www.w3.org/ns/activitystreams#Reject, http://www.w3.org/ns/activitystreams#Remove, http://www.w3.org/ns/activitystreams#Service, http://www.w3.org/ns/activitystreams#TentativeAccept, http://www.w3.org/ns/activitystreams#TentativeReject, http://www.w3.org/ns/activitystreams#Undo, http://www.w3.org/ns/activitystreams#Update, http://www.w3.org/ns/activitystreams#Video)
    at Class.add (file:///C:/Users/aaron/GitHub/AaronNGray/schema-dts/packages/schema-dts-gen/dist/src/ts/class.js:138:23)
    at toClass (file:///C:/Users/aaron/GitHub/AaronNGray/schema-dts/packages/schema-dts-gen/dist/src/transform/toClass.js:25:27)
    at BuildClasses (file:///C:/Users/aaron/GitHub/AaronNGray/schema-dts/packages/schema-dts-gen/dist/src/transform/toClass.js:109:9)
    at ProcessClasses (file:///C:/Users/aaron/GitHub/AaronNGray/schema-dts/packages/schema-dts-gen/dist/src/transform/toClass.js:125:5)
    at file:///C:/Users/aaron/GitHub/AaronNGray/schema-dts/packages/schema-dts-gen/dist/src/transform/transform.js:49:25
    at Generator.next (<anonymous>)
    at file:///C:/Users/aaron/GitHub/AaronNGray/schema-dts/packages/schema-dts-gen/dist/src/transform/transform.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (file:///C:/Users/aaron/GitHub/AaronNGray/schema-dts/packages/schema-dts-gen/dist/src/transform/transform.js:3:12)
    at WriteDeclarations (file:///C:/Users/aaron/GitHub/AaronNGray/schema-dts/packages/schema-dts-gen/dist/src/transform/transform.js:47:12)
```

**Comment by AaronNGray** [comment]
```
as:Accept a owl:Class ;
as:Activity a owl:Class ;
as:Block a owl:Class ;
as:IntransitiveActivity a owl:Class ;
as:Add a owl:Class ;
as:Announce a owl:Class ;
as:Application a owl:Class ;
as:Arrive a owl:Class ;
as:Article a owl:Class ;
as:Audio a owl:Class ;
as:Collection a owl:Class ;
as:CollectionPage a owl:Class ;
as:OrderedCollectionPage a owl:Class ;
as:Relationship a owl:Class, rdf:Statement ;
as:Create a owl:Class ;
as:Delete a owl:Class ;
as:Dislike a owl:Class ;
as:Document a owl:Class ;
as:Event a owl:Class ;
as:Flag a owl:Class ;
as:Follow a owl:Class ;
as:Group a owl:Class ;
as:Ignore a owl:Class ;
as:Image a owl:Class ;
as:Invite a owl:Class ;
as:Join a owl:Class ;
as:Leave a owl:Class ;
as:Like a owl:Class ;
as:View a owl:Class ;
as:Listen a owl:Class ;
as:Read a owl:Class ;
as:Move a owl:Class ;
as:Travel a owl:Class ;
as:Link a owl:Class ;
as:Mention a owl:Class ;
as:Note a owl:Class ;
as:Object a owl:Class ;
as:Offer a owl:Class ;
as:OrderedCollection a owl:Class ;
as:OrderedItems a owl:Class ;
as:Page a owl:Class ;
as:Person a owl:Class ;
as:Organization a owl:Class ;
as:Profile a owl:Class ;
as:Place a owl:Class ;
as:Question a owl:Class ;
as:Reject a owl:Class ;
as:Remove a owl:Class ;
as:Service a owl:Class ;
as:TentativeAccept a owl:Class ;
as:TentativeReject a owl:Class ;
as:Tombstone a owl:Class ;
as:Undo a owl:Class ;
as:Update a owl:Class ;
as:Video a owl:Class ;
```

**Comment by AaronNGray** [comment]
`schema-dts-gen` is not processing the input RDF on an RDF level into the graph store its missing the RDF semantics :-
```
as:Object a owl:Class ;
  rdfs:label "Object"@en .
```
is loosing that **as:Object** is **a** **owl:class**

where **a** is **rdf:type**

and only storing the :-
```
rdfs:label "Object"@en .
```
for as:Object

**Comment by AaronNGray** [comment]
Also `schema-dts-gen` is also storing `http://www.w3.org/ns/activitystreams#<>` for every `as:<>` reference.
